# Generated by Django 5.2 on 2025-04-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='id_producto',
            new_name='id_product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unitary_price',
            field=models.FloatField(),
        ),
    ]
